### PR TITLE
Update index.html: Fixed "Pictures of Mars"

### LINKED ISSUE #6: [BUG]: Image pop up animation timing is not good
The timing of zoom-in animation of images in 'Pictures of Mars' section does not feel right. Make it more appealing to look at.

### Issue:

- Scroll to 'Pictures of Mars' section.
- See the pictures have zoom-in animation when scrolled to viewport.
- The pictures zoom-in animation timing on scroll is not right.

### How to solve:

- Navigate to the required section in Index.html file.
- Change data-aos values and timing.

### PR DESCRIPTION
**Pull request by 0xScratch**
Fixed #6

### CODE REVIEW

**Review by hardickraj — CHANGES_REQUESTED** [review]
Do not use aos delay 200 in every image. Use the delay in such a way that images should pop in one-by-one, (not all at once).

_use delay value from "0" to "300" for four images, then start from "0" for next images_

**Comment by hardickraj** [comment]
Do these changes, and I'll merge your pr.

**Comment by 0xScratch** [comment]
Check it!

**Review by hardickraj — CHANGES_REQUESTED** [review]
Bro, dont increase the value by 2x. Increase the value by 100 only. That way it will be consistent.

_(use 00, 100, 200, 300)_

**Comment by 0xScratch** [comment]
ah ok!

**Review by hardickraj — APPROVED** [review]
Good. Will merge!

**Pull request merged**
